name = 'event_signal'
version = '1.8.0'
description = 'Library to help notify when something has changed.'
url = 'https://github.com/justengel/event_signal'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
